/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignRouteImport } from './routes/web-design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as ProjectSlugRouteImport } from './routes/project/$slug'
import { Route as OgSplatRouteImport } from './routes/og/$'
import { Route as ApiMarginRouteImport } from './routes/api/margin'

const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarginRoute = ApiMarginRouteImport.update({
  id: '/api/margin',
  path: '/api/margin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/web-design': typeof WebDesignRoute
  '/api/margin': typeof ApiMarginRoute
  '/og/$': typeof OgSplatRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/web-design': typeof WebDesignRoute
  '/api/margin': typeof ApiMarginRoute
  '/og/$': typeof OgSplatRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/web-design': typeof WebDesignRoute
  '/api/margin': typeof ApiMarginRoute
  '/og/$': typeof OgSplatRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/web-design'
    | '/api/margin'
    | '/og/$'
    | '/project/$slug'
    | '/writing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/web-design'
    | '/api/margin'
    | '/og/$'
    | '/project/$slug'
    | '/writing/$slug'
  id:
    | '__root__'
    | '/'
    | '/web-design'
    | '/api/margin'
    | '/og/$'
    | '/project/$slug'
    | '/writing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebDesignRoute: typeof WebDesignRoute
  ApiMarginRoute: typeof ApiMarginRoute
  OgSplatRoute: typeof OgSplatRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/margin': {
      id: '/api/margin'
      path: '/api/margin'
      fullPath: '/api/margin'
      preLoaderRoute: typeof ApiMarginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebDesignRoute: WebDesignRoute,
  ApiMarginRoute: ApiMarginRoute,
  OgSplatRoute: OgSplatRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
